### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by mmacedoeu** [Polymer/designer#160]
After npm install, bower install, browserify from build and npm start I got this on console after clicking on designer template tree item text-editing.html:

_currentSourceIdChanged null
http://localhost:8081/files///polymer-designer-demos/text-editing.html/ Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Fetch API cannot load http://localhost:8081/files///polymer-designer-demos/text-editing.html/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.
localhost/:1 Uncaught (in promise) TypeError: Failed to fetch
    at TypeError (native)
2designer-stage.html:414 Uncaught TypeError: Cannot read property 'selectElementAtPoint' of undefined

**Comment by mmacedoeu** [comment]
Works with Chrome Canary

**Comment by dChin84** [comment]
@mmacedoeu I have just built the repo, Try running in canary I have got a feeing this could be the issue here as they are taking advantage of some of the new api's (Document.elementFromPoint). Also if you click the polymer-designer-demos directory from the interface this produces a cors issue if you drill into the files inside and select it seems to work as described

**Comment by mmacedoeu** [comment]
I could trace it to a problem related with double slahes in uri

Em qua, 15 de jul de 2015 10:26, Daniel Chin <notifications@github.com>
escreveu:
