### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by caraya** [Polymer/designer#208]
Justin, 

Is there documentation available on how to plug in your own elements to designer? Is the only way to learn how to look at the code? I'm working on an editor project and would love to use designer as the basis

**Comment by justinfagnani** [comment]
As of now, the elements are hard-coded. I just added a project concept, which currently is nothing more than a project directory, which is intended to hold information like import URLs to make available to the element palette.

It's still very early days for Designer 2, I haven't been working on documentation so that I can try to make as much forward progress as possible. Sorry.

**Comment by caraya** [comment]
no worries... I'll see if I can get what I need by looking at the code. 

I'll close the issue for now.

**Comment by justinfagnani** [comment]
You can also join #designer-dev on Slack and I'll try to answer as many questions as possible, or document what you need. As a first step I'd recommend getting things running locally and seeing of the editing capabilities are even sufficient for you.

**Comment by caraya** [comment]
Thanks!
